# Generated by Django 3.1.7 on 2021-04-07 16:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Program Name')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RiskAnalysis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('risk', models.CharField(max_length=50, verbose_name='RISK')),
                ('sub_risk', models.CharField(max_length=50, verbose_name="RISK FACTOR's")),
                ('probability', models.CharField(choices=[('0.9', 'CASI SEGURO'), ('0.7', 'PROBABLE'), ('0.5', 'POSIBLE'), ('0.3', 'IMPROBABLE'), ('0.1', 'RARA VEZ')], default='0.9', max_length=50, verbose_name='PROBABILIDAD')),
                ('impact', models.CharField(choices=[('0.05', 'MUY BAJO'), ('0.1', 'BAJO'), ('0.2', 'MODERADO'), ('0.4', 'ALTO'), ('0.8', 'MUY ALTO')], default='0.05', max_length=50, verbose_name='IMPACTO')),
                ('risk_evaluation', models.FloatField(verbose_name='EVALUACIÓN DE RIESGO')),
                ('risk_categorization', models.CharField(choices=[('Slow Risk', 'Slow Risk'), ('Moderate Risk', 'Moderate Risk'), ('High Risk', 'High Risk')], max_length=50, verbose_name='RISK CATEGORIZATION')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.program')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('risk_rate', models.FloatField(verbose_name='Tasa Riesgo')),
                ('inflation_rate', models.FloatField(verbose_name='Tasa Inflacion')),
                ('initial_investment', models.FloatField(verbose_name='Inversion Inicial')),
                ('years', models.IntegerField(verbose_name='AÑOS')),
                ('total_income', models.FloatField(verbose_name='TOTAL INGRESOS')),
                ('total_expense', models.FloatField(verbose_name='TOTAL EGRESOS')),
                ('net_cash_flow', models.FloatField(verbose_name='Flujo de Efectivo Neto')),
                ('cash_flow_at_present_value', models.FloatField(verbose_name='Flujo de efectivo a Valor Presente')),
                ('accumulated_cash_flow', models.FloatField(verbose_name='Flujo de Efectivo Acumulado')),
                ('vpn', models.FloatField(verbose_name='VPN')),
                ('recovery_period', models.FloatField(verbose_name='Periodo de Recuperación')),
                ('interal_rate_of_return', models.FloatField(verbose_name='Tasa Interna de Retorno')),
                ('return_on_investment', models.FloatField(verbose_name='Retorno sobre la Inversión ROI')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.program')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Categorization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business', models.CharField(max_length=50, verbose_name='EMPRESA')),
                ('code', models.IntegerField(verbose_name='CÓDIGO')),
                ('project', models.CharField(max_length=50, verbose_name='PROYECTO')),
                ('project_detail', models.CharField(max_length=50, verbose_name='DETALLE DE PROYECTO')),
                ('year', models.CharField(choices=[('2020', 2020), ('2021', 2021), ('2022', 2022)], default='2021', max_length=50, verbose_name='AÑO')),
                ('category', models.CharField(choices=[('must_do', 'Must do'), ('wont_do', 'Won’t do'), ('may_do', 'May do')], default='must_do', max_length=50, verbose_name='CATEGORIZACIÓN')),
                ('dimension', models.CharField(choices=[('customers', 'Clientes'), ('strategy', 'Estrategia'), ('technology', 'Tecnología'), ('operations', 'Operaciones'), ('culture', 'Cultura'), ('data', 'Datos'), ('clients_strategy', 'Clientes/Estrategia'), ('clients_technology', 'Clientes/Tecnología'), ('clients_culture', 'Clientes/Cultura'), ('clients_data', 'Clientes/Datos')], default='customers', max_length=50, verbose_name='DIMENSIÓN')),
                ('strategic_objective', models.CharField(max_length=50, verbose_name='OBJETIVO ESTRATÉGICO')),
                ('total_budget', models.FloatField(verbose_name='PRESUPUESTO TOTAL')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.program')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
