# Generated by Django 3.1.4 on 2021-04-10 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210410_0305'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='score',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
