# Generated by Django 3.1.4 on 2021-04-30 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_questions_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='optimizations',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='evaluation',
            name='inflation_rate',
            field=models.FloatField(verbose_name='Tasa de Interés'),
        ),
        migrations.AlterField(
            model_name='evaluation',
            name='risk_rate',
            field=models.FloatField(verbose_name='Tasa'),
        ),
    ]
